import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  deleteButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  infoCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#4F46E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  avatarText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  clientName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
    marginBottom: 8,
  },
  lockedBadge: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
  },
  unlockedBadge: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  adminModeBadge: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    marginTop: 6,
  },
  adminModeOffBadge: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    marginTop: 6,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '600',
  },
  lockedText: {
    color: '#EF4444',
  },
  unlockedText: {
    color: '#10B981',
  },
  adminModeText: {
    color: '#3B82F6',
  },
  adminModeOffText: {
    color: '#F59E0B',
  },
  regCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  regCode: {
    fontSize: 14,
    color: '#64748B',
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    gap: 6,
  },
  copyText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  generateKeyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4F46E5',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  generateKeyButtonDisabled: {
    backgroundColor: '#374151',
    opacity: 0.7,
  },
  generateKeyButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  creditBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 4,
    gap: 4,
  },
  creditBadgeText: {
    color: '#F59E0B',
    fontSize: 12,
    fontWeight: '600',
  },
  regCodeHidden: {
    fontSize: 14,
    color: '#64748B',
    fontStyle: 'italic',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#CBD5E1',
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    gap: 12,
  },
  infoText: {
    fontSize: 15,
    color: '#fff',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#4F46E520',
    borderRadius: 8,
  },
  editButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4F46E5',
  },
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  locationText: {
    fontSize: 15,
    color: '#3B82F6',
  },
  notRegistered: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  notRegisteredText: {
    fontSize: 15,
    color: '#F59E0B',
  },
  fetchPriceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#4F46E520',
    borderRadius: 8,
  },
  fetchPriceText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4F46E5',
  },
  priceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B98120',
    borderRadius: 16,
    padding: 20,
    gap: 16,
  },
  priceIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#10B98130',
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceInfo: {
    flex: 1,
  },
  priceLabel: {
    fontSize: 13,
    color: '#94A3B8',
    marginBottom: 4,
  },
  priceValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#10B981',
  },
  priceDate: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
  },
  noPriceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 20,
    gap: 12,
  },
  noPriceText: {
    fontSize: 14,
    color: '#64748B',
  },
  // Tab styles
  tabContainer: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 4,
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 4,
    borderWidth: 1,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  tabButtonActive: {
    backgroundColor: '#4F46E520',
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#94A3B8',
  },
  tabButtonTextActive: {
    color: '#4F46E5',
    fontWeight: '600',
  },
  // Loan section styles
  loanHeaderButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editLoanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4F46E520',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  editLoanBtnText: {
    color: '#4F46E5',
    fontSize: 12,
    fontWeight: '600',
  },
  addNewLoanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B98120',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  addNewLoanBtnText: {
    color: '#10B981',
    fontSize: 12,
    fontWeight: '600',
  },
  recordPaymentBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#10B98120',
    borderRadius: 8,
  },
  recordPaymentBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#10B981',
  },
  loanProgressCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  loanProgressBar: {
    height: 8,
    backgroundColor: '#0F172A',
    borderRadius: 4,
    overflow: 'hidden',
  },
  loanProgressFill: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 4,
  },
  loanProgressText: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 6,
    textAlign: 'right',
  },
  loanStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    gap: 16,
  },
  loanStatItem: {
    flex: 1,
    minWidth: '40%',
  },
  loanStatLabel: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 4,
  },
  loanStatValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  overdueAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    padding: 12,
    backgroundColor: '#EF444420',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  overdueAlertText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#EF4444',
  },
  // Late fee styles
  lateFeeCard: {
    backgroundColor: '#DC262615',
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#DC262630',
  },
  lateFeeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  lateFeeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#DC2626',
  },
  lateFeeDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  lateFeeDetailItem: {
    flex: 1,
  },
  lateFeeLabel: {
    fontSize: 12,
    color: '#94A3B8',
    marginBottom: 4,
  },
  lateFeeValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#DC2626',
  },
  lateFeeValueTotal: {
    fontSize: 18,
    fontWeight: '700',
    color: '#F59E0B',
  },
  autoLockWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#DC262630',
  },
  autoLockWarningText: {
    fontSize: 12,
    color: '#F59E0B',
    fontWeight: '600',
  },
  // Contract action styles
  contractActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
  },
  contractButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: '#4F46E520',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4F46E5',
  },
  contractButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4F46E5',
  },
  downloadButton: {
    backgroundColor: '#3B82F620',
    borderColor: '#3B82F6',
  },
  downloadButtonText: {
    color: '#3B82F6',
  },
  shareButton: {
    backgroundColor: '#10B98120',
    borderColor: '#10B981',
  },
  shareButtonText: {
    color: '#10B981',
  },
  // Loan History styles
  loanHistoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  loanHistoryHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loanHistorySearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
    gap: 8,
  },
  loanHistorySearchInput: {
    flex: 1,
    fontSize: 14,
    paddingVertical: 0,
  },
  loanHistoryContent: {
    marginTop: 12,
  },
  emptyLoanHistory: {
    alignItems: 'center',
    paddingVertical: 24,
    gap: 8,
  },
  emptyLoanHistoryText: {
    fontSize: 14,
  },
  loanHistoryCard: {
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
  },
  loanHistoryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  loanHistoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  loanHistoryBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  loanHistoryDate: {
    fontSize: 12,
  },
  loanHistoryDetails: {
    gap: 8,
  },
  loanHistoryDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  loanHistoryLabel: {
    fontSize: 13,
  },
  loanHistoryValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  // Payment history styles
  paymentHistoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  paymentHistoryLeft: {
    gap: 2,
  },
  paymentHistoryAmount: {
    fontSize: 16,
    fontWeight: '600',
  },
  paymentHistoryDate: {
    fontSize: 12,
  },
  paymentHistoryRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  paymentMethodBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  paymentMethodLabel: {
    fontSize: 11,
    fontWeight: '500',
  },
  paymentHistoryNotes: {
    fontSize: 11,
    maxWidth: 140,
  },
  // Action button styles
  actionsSection: {
    marginBottom: 40,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    gap: 8,
  },
  lockButton: {
    backgroundColor: '#EF4444',
  },
  unlockButton: {
    backgroundColor: '#10B981',
  },
  warningButton: {
    backgroundColor: '#F59E0B',
  },
  allowUninstallButton: {
    backgroundColor: '#8B5CF6',
  },
  setupLoanButton: {
    backgroundColor: '#4F46E5',
  },
  renewLoanButton: {
    backgroundColor: '#10B981',
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#94A3B8',
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 16,
    fontSize: 16,
    color: '#fff',
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  modalCancelButton: {
    backgroundColor: '#334155',
  },
  modalConfirmButton: {
    backgroundColor: '#F59E0B',
  },
  lockConfirmButton: {
    backgroundColor: '#EF4444',
  },
  paymentConfirmButton: {
    backgroundColor: '#10B981',
  },
  modalCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  modalConfirmText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#94A3B8',
    marginBottom: 8,
  },
  paymentInput: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    color: '#fff',
    borderWidth: 1,
    borderColor: '#334155',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  methodButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  methodButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#0F172A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
  },
  methodButtonActive: {
    backgroundColor: '#10B98120',
    borderColor: '#10B981',
  },
  methodButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#94A3B8',
  },
  methodButtonTextActive: {
    color: '#10B981',
  },
  // Edit Loan preview styles
  previewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4F46E515',
    borderWidth: 1,
    borderColor: '#4F46E5',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
    gap: 8,
  },
  previewButtonText: {
    color: '#4F46E5',
    fontSize: 14,
    fontWeight: '600',
  },
  loanPreviewCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  loanPreviewTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#10B981',
    marginBottom: 12,
    textAlign: 'center',
  },
  loanPreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  loanPreviewItem: {
    width: '47%',
    backgroundColor: '#0F172A',
    borderRadius: 8,
    padding: 12,
  },
  loanPreviewLabel: {
    fontSize: 11,
    color: '#64748B',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  loanPreviewValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
});
