import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'no' | 'sv' | 'da' | 'fi' | 'et' | 'lv' | 'lt' | 'de_at' | 'cs' | 'pl' | 'de_ch' | 'es' | 'de' | 'fr' | 'it';

export interface LanguageOption {
  code: Language;
  name: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', flag: 'GB' },
  { code: 'no', name: 'Norsk', flag: 'NO' },
  { code: 'sv', name: 'Svenska', flag: 'SE' },
  { code: 'da', name: 'Dansk', flag: 'DK' },
  { code: 'fi', name: 'Suomi', flag: 'FI' },
  { code: 'et', name: 'Eesti', flag: 'EE' },
  { code: 'lv', name: 'Latvie\u0161u', flag: 'LV' },
  { code: 'lt', name: 'Lietuvi\u0173', flag: 'LT' },
  { code: 'de_at', name: '\u00D6sterreichisch', flag: 'AT' },
  { code: 'cs', name: '\u010Ce\u0161tina', flag: 'CZ' },
  { code: 'pl', name: 'Polski', flag: 'PL' },
  { code: 'de_ch', name: 'Schweizerdeutsch', flag: 'CH' },
  { code: 'es', name: 'Espa\u00F1ol', flag: 'ES' },
  { code: 'de', name: 'Deutsch', flag: 'DE' },
  { code: 'fr', name: 'Fran\u00E7ais', flag: 'FR' },
  { code: 'it', name: 'Italiano', flag: 'IT' },
];

// Translation entries: key -> { lang_code: translated_string }
// Falls back: current language -> de (for de_at/de_ch) -> en
const translations: Record<string, Partial<Record<Language, string>>> = {
  // ============ HOME SCREEN ============
  appTitle: {
    en: 'Loan Lock System', et: 'Laenu lukustuss\u00FCsteem', de: 'Kreditsperre-System', de_at: 'Kreditsperre-System', de_ch: 'Kreditsperre-System',
    fr: 'Syst\u00E8me de verrouillage de pr\u00EAt', es: 'Sistema de bloqueo de pr\u00E9stamo', it: 'Sistema di blocco prestito',
    no: 'L\u00E5nesperresystem', sv: 'L\u00E5nesp\u00E4rrsystem', da: 'L\u00E5nesp\u00E6rresystem', fi: 'Lainanlukitusjärjestelmä',
    lv: 'Aizdevuma blo\u0137\u0113\u0161anas sist\u0113ma', lt: 'Paskolos u\u017Erakinimo sistema', cs: 'Syst\u00E9m z\u00E1mku p\u016Fj\u010Dky', pl: 'System blokady po\u017Cyczki',
  },
  appSubtitle: {
    en: 'Phone Lock Management for Loans', et: 'Telefoni lukustuslahendus laenude jaoks',
    de: 'Telefonsperre-Verwaltung f\u00FCr Kredite', fr: 'Gestion du verrouillage t\u00E9l\u00E9phone pour pr\u00EAts',
    no: 'Telefonl\u00E5sh\u00E5ndtering for l\u00E5n', sv: 'Telefonl\u00E5shantering f\u00F6r l\u00E5n',
  },
  selectMode: { en: 'Select Your Mode', et: 'Vali re\u017Eiim', de: 'Modus w\u00E4hlen', fr: 'S\u00E9lectionnez votre mode', es: 'Seleccione su modo', it: 'Seleziona modalit\u00E0', no: 'Velg modus', sv: 'V\u00E4lj l\u00E4ge', da: 'V\u00E6lg tilstand', fi: 'Valitse tila', lv: 'Izv\u0113lieties re\u017E\u012Bmu', lt: 'Pasirinkite re\u017Eim\u0105', cs: 'Vyberte re\u017Eim', pl: 'Wybierz tryb' },
  adminPanel: { en: 'Admin Panel', et: 'Administraatori paneel', de: 'Admin-Panel', fr: 'Panneau admin', es: 'Panel de administraci\u00F3n', it: 'Pannello admin', no: 'Adminpanel', sv: 'Adminpanel', da: 'Adminpanel', fi: 'Hallintapaneeli' },
  adminDescription: { en: 'Manage clients, lock/unlock devices, send warnings, and track locations', et: 'Halda kliente, lukusta/ava seadmeid, saada hoiatusi ja j\u00E4lgi asukohti' },
  clientDevice: { en: 'Client Device', et: 'Kliendi seade', de: 'Kundengerät', fr: 'Appareil client', es: 'Dispositivo cliente', it: 'Dispositivo cliente', no: 'Klientenhet', sv: 'Klientenhet', da: 'Klientenhed', fi: 'Asiakaslaite' },
  clientDescription: { en: 'Register your device, view loan status, and manage your account', et: 'Registreeri oma seade, vaata laenu staatust ja halda oma kontot' },
  secureSystem: { en: 'Secure Loan Management System', et: 'Turvaline laenuhalduss\u00FCsteem' },

  // ============ AUTH ============
  adminLogin: { en: 'Admin Login', et: 'Administraatori sisselogimine', de: 'Admin-Anmeldung', fr: 'Connexion admin', es: 'Inicio de sesi\u00F3n admin', it: 'Login admin', no: 'Admin innlogging', sv: 'Admin inloggning', da: 'Admin login', fi: 'Ylläpitäjän kirjautuminen' },
  signInToManage: { en: 'Sign in to manage your clients', et: 'Logi sisse, et hallata oma kliente' },
  username: { en: 'Username', et: 'Kasutajanimi', de: 'Benutzername', fr: "Nom d'utilisateur", es: 'Usuario', it: 'Nome utente', no: 'Brukernavn', sv: 'Användarnamn', da: 'Brugernavn', fi: 'Käyttäjänimi', lv: 'Lietotājvārds', lt: 'Naudotojo vardas', cs: 'Uživatelské jméno', pl: 'Nazwa użytkownika' },
  password: { en: 'Password', et: 'Parool', de: 'Passwort', fr: 'Mot de passe', es: 'Contraseña', it: 'Password', no: 'Passord', sv: 'Lösenord', da: 'Adgangskode', fi: 'Salasana', lv: 'Parole', lt: 'Slaptažodis', cs: 'Heslo', pl: 'Hasło' },
  signIn: { en: 'Sign In', et: 'Logi sisse', de: 'Anmelden', fr: 'Se connecter', es: 'Iniciar sesi\u00F3n', it: 'Accedi', no: 'Logg inn', sv: 'Logga in', da: 'Log ind', fi: 'Kirjaudu', lv: 'Pieteikties', lt: 'Prisijungti', cs: 'Přihlásit', pl: 'Zaloguj się' },
  login: { en: 'Login', et: 'Logi sisse', de: 'Anmelden', fr: 'Connexion', es: 'Entrar', it: 'Accedi', no: 'Logg inn', sv: 'Logga in' },
  error: { en: 'Error', et: 'Viga', de: 'Fehler', fr: 'Erreur', es: 'Error', it: 'Errore', no: 'Feil', sv: 'Fel', da: 'Fejl', fi: 'Virhe', lv: 'Kļūda', lt: 'Klaida', cs: 'Chyba', pl: 'Błąd' },
  fillAllFields: { en: 'Please fill in all fields', et: 'Palun t\u00E4ida k\u00F5ik v\u00E4ljad', de: 'Bitte alle Felder ausfüllen', fr: 'Veuillez remplir tous les champs' },
  ok: { en: 'OK', et: 'OK', de: 'OK', fr: 'OK', es: 'OK', it: 'OK' },
  retry: { en: 'Retry', et: 'Proovi uuesti', de: 'Wiederholen', fr: 'Réessayer', es: 'Reintentar', it: 'Riprova', no: 'Prøv igjen', sv: 'Försök igen' },

  // ============ DASHBOARD ============
  welcomeBack: { en: 'Welcome back,', et: 'Tere tulemast tagasi,', de: 'Willkommen zurück,', fr: 'Bon retour,', es: 'Bienvenido de vuelta,', it: 'Bentornato,', no: 'Velkommen tilbake,', sv: 'Välkommen tillbaka,', da: 'Velkommen tilbage,', fi: 'Tervetuloa takaisin,' },
  dashboardOverview: { en: 'Dashboard Overview', et: '\u00DClevaade', de: 'Dashboard-Übersicht', fr: 'Aperçu du tableau de bord' },
  totalClients: { en: 'Total Clients', et: 'Kliente kokku', de: 'Kunden gesamt', fr: 'Total clients', es: 'Total clientes', it: 'Totale clienti', no: 'Totalt klienter', sv: 'Totalt klienter' },
  lockedDevices: { en: 'Locked Devices', et: 'Lukustatud seadmed', de: 'Gesperrte Geräte', fr: 'Appareils verrouillés' },
  registered: { en: 'Registered', et: 'Registreeritud', de: 'Registriert', fr: 'Enregistrés', es: 'Registrados', it: 'Registrati', no: 'Registrert', sv: 'Registrerade' },
  unlocked: { en: 'Unlocked', et: 'Avatud', de: 'Entsperrt', fr: 'Déverrouillés', es: 'Desbloqueados', it: 'Sbloccati', no: 'Ulåst', sv: 'Olåst' },
  quickActions: { en: 'Quick Actions', et: 'Kiirtoimingud', de: 'Schnellaktionen', fr: 'Actions rapides' },
  copy: { en: 'Copy', et: 'Kopeeri', de: 'Kopieren', fr: 'Copier', es: 'Copiar', it: 'Copia', no: 'Kopier', sv: 'Kopiera' },
  copied: { en: 'Code copied', et: 'Kood kopeeritud', de: 'Code kopiert', fr: 'Code copié' },
  viewClients: { en: 'View Clients', et: 'Vaata kliente', de: 'Kunden anzeigen', fr: 'Voir les clients' },
  manageClients: { en: 'Manage all registered clients', et: 'Halda k\u00F5iki registreeritud kliente' },
  addNewClient: { en: 'Add New Client', et: 'Lisa uus klient', de: 'Neuen Kunden hinzuf\u00FCgen', fr: 'Ajouter un nouveau client', es: 'Añadir nuevo cliente', it: 'Aggiungi nuovo cliente', no: 'Legg til ny klient', sv: 'Lägg till ny klient' },
  registerNewClient: { en: 'Register a new client', et: 'Registreeri uus klient' },
  logout: { en: 'Logout', et: 'Logi v\u00E4lja', de: 'Abmelden', fr: 'D\u00E9connexion', es: 'Cerrar sesi\u00F3n', it: 'Esci', no: 'Logg ut', sv: 'Logga ut', da: 'Log ud', fi: 'Kirjaudu ulos' },
  logoutConfirm: { en: 'Are you sure you want to logout?', et: 'Kas oled kindel, et soovid v\u00E4lja logida?', de: 'Möchten Sie sich wirklich abmelden?' },
  cancel: { en: 'Cancel', et: 'T\u00FChista', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', it: 'Annulla', no: 'Avbryt', sv: 'Avbryt', da: 'Annuller', fi: 'Peruuta', lv: 'Atcelt', lt: 'Atšaukti', cs: 'Zrušit', pl: 'Anuluj' },

  // ============ CLIENTS ============
  clients: { en: 'Clients', et: 'Kliendid', de: 'Kunden', fr: 'Clients', es: 'Clientes', it: 'Clienti', no: 'Klienter', sv: 'Klienter', da: 'Klienter', fi: 'Asiakkaat' },
  searchPlaceholder: { en: 'Search by name, phone, or email', et: 'Otsi nime, telefoni v\u00F5i e-posti j\u00E4rgi' },
  all: { en: 'All', et: 'K\u00F5ik', de: 'Alle', fr: 'Tous', es: 'Todos', it: 'Tutti', no: 'Alle', sv: 'Alla', da: 'Alle', fi: 'Kaikki' },
  locked: { en: 'Locked', et: 'Lukustatud', de: 'Gesperrt', fr: 'Verrouillé', es: 'Bloqueado', it: 'Bloccato', no: 'Låst', sv: 'Låst' },
  emi: { en: 'Loan', et: 'Laen', de: 'Kredit', fr: 'Prêt', es: 'Préstamo', it: 'Prestito', no: 'Lån', sv: 'Lån', da: 'Lån', fi: 'Laina' },
  pending: { en: 'Pending', et: 'Ootel', de: 'Ausstehend', fr: 'En attente', es: 'Pendiente', it: 'In attesa', no: 'Ventende', sv: 'Väntande' },
  code: { en: 'Code', et: 'Kood', de: 'Code', fr: 'Code', es: 'C\u00F3digo', it: 'Codice', no: 'Kode', sv: 'Kod' },
  noClientsFound: { en: 'No clients found', et: 'Kliente ei leitud', de: 'Keine Kunden gefunden', fr: 'Aucun client trouvé' },

  // ============ ADD CLIENT ============
  fullName: { en: 'Full Name', et: 'T\u00E4isnimi', de: 'Vollst\u00E4ndiger Name', fr: 'Nom complet', es: 'Nombre completo', it: 'Nome completo', no: 'Fullt navn', sv: 'Fullständigt namn' },
  enterClientName: { en: "Enter client's name", et: 'Sisesta kliendi nimi' },
  phoneNumber: { en: 'Phone Number', et: 'Telefoninumber', de: 'Telefonnummer', fr: 'Numéro de téléphone', es: 'Número de teléfono', it: 'Numero di telefono', no: 'Telefonnummer', sv: 'Telefonnummer' },
  enterPhone: { en: 'Enter phone number', et: 'Sisesta telefoninumber' },
  emailAddress: { en: 'Email Address', et: 'E-posti aadress', de: 'E-Mail-Adresse', fr: 'Adresse e-mail' },
  enterEmail: { en: 'Enter email address', et: 'Sisesta e-posti aadress' },
  emiAmount: { en: 'Loan Amount', et: 'Laenusumma', de: 'Kreditbetrag', fr: 'Montant du prêt', es: 'Monto del préstamo', it: 'Importo del prestito', no: 'Lånebeløp', sv: 'Lånebelopp' },
  enterEmiAmount: { en: 'Enter loan amount', et: 'Sisesta laenusumma' },
  emiDueDate: { en: 'Loan Due Date', et: 'Laenu t\u00E4htaeg', de: 'Kreditfälligkeitsdatum', fr: 'Date d\u2019échéance' },
  createClient: { en: 'Create Client', et: 'Loo klient', de: 'Kunden erstellen', fr: 'Créer un client' },
  registrationCodeInfo: { en: 'A unique registration code will be generated. Share this code with the client to register their device.', et: 'Genereeritakse unikaalne registreerimiskood. Jaga seda koodi kliendiga, et ta saaks oma seadme registreerida.' },
  success: { en: 'Success', et: '\u00D5nnestus', de: 'Erfolg', fr: 'Succès', es: 'Éxito', it: 'Successo', no: 'Suksess', sv: 'Framgång' },
  clientCreated: { en: 'Client created!', et: 'Klient loodud!' },
  registrationCode: { en: 'Registration Code', et: 'Registreerimiskood', de: 'Registrierungscode', fr: 'Code d\u2019enregistrement' },
  shareCodeMessage: { en: 'Share this code with the client to register their device.', et: 'Jaga seda koodi kliendiga, et ta saaks oma seadme registreerida.' },

  // ============ CLIENT DETAILS ============
  clientDetails: { en: 'Client Details', et: 'Kliendi andmed', de: 'Kundendetails', fr: 'Détails du client' },
  contactInfo: { en: 'Contact Information', et: 'Kontaktandmed', de: 'Kontaktinformationen', fr: 'Informations de contact' },
  emiDetails: { en: 'Loan Details', et: 'Laenu andmed', de: 'Kreditdetails', fr: 'Détails du prêt' },
  amount: { en: 'Amount', et: 'Summa', de: 'Betrag', fr: 'Montant', es: 'Monto', it: 'Importo', no: 'Beløp', sv: 'Belopp' },
  dueDate: { en: 'Due Date', et: 'T\u00E4htaeg', de: 'Fälligkeitsdatum', fr: 'Date d\u2019échéance' },
  notSet: { en: 'Not set', et: 'Pole m\u00E4\u00E4ratud', de: 'Nicht festgelegt', fr: 'Non défini' },
  deviceInfo: { en: 'Device Information', et: 'Seadme info', de: 'Geräteinfo', fr: 'Informations sur l\u2019appareil' },
  viewLocationOnMap: { en: 'View Location on Map', et: 'Vaata asukohta kaardil' },
  locationNotAvailable: { en: 'Location not available', et: 'Asukoht pole saadaval' },
  deviceNotRegistered: { en: 'Device not registered yet', et: 'Seade pole veel registreeritud' },
  lockDevice: { en: 'Lock Device', et: 'Lukusta seade', de: 'Gerät sperren', fr: 'Verrouiller l\u2019appareil', es: 'Bloquear dispositivo', it: 'Blocca dispositivo', no: 'Lås enhet', sv: 'Lås enhet' },
  unlockDevice: { en: 'Unlock Device', et: 'Ava seade', de: 'Gerät entsperren', fr: 'Déverrouiller', es: 'Desbloquear', it: 'Sblocca', no: 'Lås opp enhet', sv: 'Lås upp enhet' },
  sendWarning: { en: 'Send Warning', et: 'Saada hoiatus', de: 'Warnung senden', fr: 'Envoyer un avertissement' },
  enterWarningMessage: { en: 'Enter warning message', et: 'Sisesta hoiatusteade' },
  send: { en: 'Send', et: 'Saada', de: 'Senden', fr: 'Envoyer', es: 'Enviar', it: 'Invia', no: 'Send', sv: 'Skicka' },
  customizeLockMessage: { en: 'Customize the lock message shown to the client', et: 'Kohanda lukustusteadet, mis kuvatakse kliendile' },
  enterLockMessage: { en: 'Enter lock message', et: 'Sisesta lukustusteade' },
  lock: { en: 'Lock', et: 'Lukusta', de: 'Sperren', fr: 'Verrouiller', es: 'Bloquear', it: 'Blocca' },
  deleteClient: { en: 'Delete Client', et: 'Kustuta klient', de: 'Kunden löschen', fr: 'Supprimer le client' },
  deleteConfirm: { en: 'Are you sure you want to delete this client? This action cannot be undone.', et: 'Kas oled kindel, et soovid selle kliendi kustutada? Seda toimingut ei saa tagasi v\u00F5tta.' },
  delete: { en: 'Delete', et: 'Kustuta', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', it: 'Elimina', no: 'Slett', sv: 'Radera' },
  deviceLockedSuccess: { en: 'Device locked successfully', et: 'Seade lukustatud edukalt' },
  deviceUnlockedSuccess: { en: 'Device unlocked successfully', et: 'Seade avatud edukalt' },
  warningSentSuccess: { en: 'Warning sent successfully', et: 'Hoiatus saadetud edukalt' },
  clientDeletedSuccess: { en: 'Client deleted successfully', et: 'Klient kustutatud edukalt' },
  unlockConfirm: { en: 'Are you sure you want to unlock this device?', et: 'Kas oled kindel, et soovid selle seadme avada?' },

  // ============ CLIENT REGISTRATION ============
  registerDevice: { en: 'Register Device', et: 'Registreeri seade', de: 'Gerät registrieren', fr: 'Enregistrer l\u2019appareil' },
  enterRegistrationCode: { en: 'Enter the registration code provided by your loan provider to link your device', et: 'Sisesta oma laenu pakkuja antud registreerimiskood, et siduda oma seade' },
  enterCode: { en: 'Enter Code', et: 'Sisesta kood', de: 'Code eingeben', fr: 'Entrez le code' },
  deviceInformation: { en: 'Device Information', et: 'Seadme informatsioon' },
  noCodeHelp: { en: "Don't have a code? Contact your loan provider to get your unique registration code.", et: 'Pole koodi? V\u00F5ta \u00FChendust oma laenu pakkujaga, et saada oma unikaalne registreerimiskood.' },
  deviceRegisteredSuccess: { en: 'Device registered successfully!', et: 'Seade registreeritud edukalt!' },
  deviceAdminPermissionPrompt: { en: 'Device registered! Please grant Device Admin permission in the next screen to complete setup.', et: 'Seade registreeritud! Palun anna j\u00E4rgmises vaates Device Admin \u00F5igused, et seadistus l\u00F5pule viia.' },
  checkingRegistration: { en: 'Checking registration...', et: 'Kontrollin registreerimist...' },

  // ============ CLIENT HOME ============
  welcome: { en: 'Welcome,', et: 'Tere tulemast,', de: 'Willkommen,', fr: 'Bienvenue,', es: 'Bienvenido,', it: 'Benvenuto,', no: 'Velkommen,', sv: 'Välkommen,' },
  deviceStatus: { en: 'Device Status', et: 'Seadme staatus', de: 'Gerätestatus', fr: 'Statut de l\u2019appareil' },
  deviceActiveNormal: { en: 'Your device is active and working normally', et: 'Sinu seade on aktiivne ja t\u00F6\u00F6tab normaalselt' },
  monthlyEmi: { en: 'Monthly EMI', et: 'Igakuine EMI', de: 'Monatliche Rate', fr: 'Mensualité' },
  contactSupport: { en: 'Contact Support', et: 'V\u00F5ta \u00FChendust toega', de: 'Support kontaktieren', fr: 'Contacter le support' },
  getHelp: { en: 'Get help with your account', et: 'Saa abi oma kontoga' },
  refreshStatus: { en: 'Refresh Status', et: 'V\u00E4rskenda staatust', de: 'Status aktualisieren', fr: 'Actualiser le statut' },
  checkForUpdates: { en: 'Check for updates', et: 'Kontrolli uuendusi' },
  warning: { en: 'Warning', et: 'Hoiatus', de: 'Warnung', fr: 'Avertissement', es: 'Advertencia', it: 'Avvertimento', no: 'Advarsel', sv: 'Varning' },
  loadingAccount: { en: 'Loading your account...', et: 'Laadin sinu kontot...' },

  // ============ LOCK SCREEN ============
  deviceLocked: { en: 'Device Locked', et: 'Seade lukustatud', de: 'Gerät gesperrt', fr: 'Appareil verrouillé', es: 'Dispositivo bloqueado', it: 'Dispositivo bloccato', no: 'Enhet låst', sv: 'Enhet låst' },
  pendingAmount: { en: 'Pending Amount', et: 'V\u00F5lgnevus', de: 'Ausstehender Betrag', fr: 'Montant en attente' },
  clearEmiToUnlock: { en: 'Please clear your pending loan balance to unlock your device', et: 'Palun tasu oma laenu v\u00F5lgnevus, et avada oma seade' },
  howToContact: { en: 'How would you like to contact support?', et: 'Kuidas soovid \u00FChendust v\u00F5tta?' },
  call: { en: 'Call', et: 'Helista', de: 'Anrufen', fr: 'Appeler', es: 'Llamar', it: 'Chiama', no: 'Ring', sv: 'Ring' },
  email: { en: 'Email', et: 'E-post', de: 'E-Mail', fr: 'E-mail', es: 'Correo', it: 'Email', no: 'E-post', sv: 'E-post' },

  // ============ SETTINGS ============
  settings: { en: 'Settings', et: 'Seaded', de: 'Einstellungen', fr: 'Paramètres', es: 'Configuración', it: 'Impostazioni', no: 'Innstillinger', sv: 'Inställningar', da: 'Indstillinger', fi: 'Asetukset' },
  language: { en: 'Language', et: 'Keel', de: 'Sprache', fr: 'Langue', es: 'Idioma', it: 'Lingua', no: 'Språk', sv: 'Språk', da: 'Sprog', fi: 'Kieli', lv: 'Valoda', lt: 'Kalba', cs: 'Jazyk', pl: 'Język' },
  currency: { en: 'Currency', et: 'Valuuta', de: 'Währung', fr: 'Devise', es: 'Moneda', it: 'Valuta', no: 'Valuta', sv: 'Valuta', da: 'Valuta', fi: 'Valuutta', lv: 'Valūta', lt: 'Valiuta', cs: 'Měna', pl: 'Waluta' },
  estonian: { en: 'Estonian', et: 'Eesti' },
  english: { en: 'English', et: 'Inglise' },
  unregisterDevice: { en: 'Unregister Device', et: 'T\u00FChista seadme registreerimine' },
  unregisterConfirm: { en: 'Are you sure you want to unregister this device? You will need to re-register with a new code.', et: 'Kas oled kindel, et soovid selle seadme registreerimise t\u00FChistada? Pead uuesti registreerima uue koodiga.' },
  unregister: { en: 'Unregister', et: 'T\u00FChista' },
  defaultLockMessage: { en: 'Your device has been locked due to pending loan payment.', et: 'Teie seade on maksmata laenumakse t\u00F5ttu lukustatud.' },
  staySignedIn: { en: 'Stay signed in', et: 'Hoia sisse logitud' },
  adminManagement: { en: 'Admin Management', et: 'Administraatori haldus' },
  createNewAdmin: { en: 'Create New Admin', et: 'Loo uus administraator' },
  newAdminUsername: { en: 'New Admin Username', et: 'Uue administraatori kasutajanimi' },
  newAdminPassword: { en: 'New Admin Password', et: 'Uue administraatori parool' },
  createAdmin: { en: 'Create Admin', et: 'Loo administraator' },
  changePassword: { en: 'Change Password', et: 'Muuda parooli', de: 'Passwort ändern', fr: 'Changer le mot de passe' },
  currentPassword: { en: 'Current Password', et: 'Praegune parool' },
  newPassword: { en: 'New Password', et: 'Uus parool' },
  updatePassword: { en: 'Update Password', et: 'Uuenda parooli' },
  existingAdmins: { en: 'Existing Admins', et: 'Olemasolevad administraatorid' },
  adminCreatedSuccess: { en: 'Admin created successfully!', et: 'Administraator loodud edukalt!' },
  passwordChangedSuccess: { en: 'Password changed successfully!', et: 'Parool muudetud edukalt!' },
  passwordMinLength: { en: 'Password must be at least 6 characters', et: 'Parool peab olema v\u00E4hemalt 6 t\u00E4hem\u00E4rki' },
  adminDeletedSuccess: { en: 'Admin deleted successfully', et: 'Administraator kustutatud edukalt' },
  deleteAdminConfirm: { en: 'Are you sure you want to delete this admin?', et: 'Kas oled kindel, et soovid selle administraatori kustutada?' },
  cannotDeleteSelf: { en: 'You cannot delete your own account', et: 'Te ei saa oma kontot kustutada' },
  createdAt: { en: 'Created At', et: 'Loodud' },

  // ============ DEVICE PRICE ============
  devicePrice: { en: 'Device Price', et: 'Seadme hind' },
  fetchPrice: { en: 'Fetch Price', et: 'Hangi hind', de: 'Preis abrufen', fr: 'Obtenir le prix' },
  usedPrice: { en: 'Used Price', et: 'Kasutatud hind' },
  estimatedValue: { en: 'Estimated Value', et: 'Hinnanguline v\u00E4\u00E4rtus', de: 'Geschätzter Wert', fr: 'Valeur estimée' },
  priceNotFetched: { en: 'Price not fetched yet', et: 'Hinda pole veel hangitud' },
  editDeviceInfo: { en: 'Edit Device Info', et: 'Muuda seadme infot' },
  deviceMake: { en: 'Make', et: 'Tootja' },
  deviceModel: { en: 'Model', et: 'Mudel' },
  price: { en: 'Price', et: 'Hind', de: 'Preis', fr: 'Prix', es: 'Precio', it: 'Prezzo', no: 'Pris', sv: 'Pris' },
  saveChanges: { en: 'Save Changes', et: 'Salvesta muudatused', de: 'Änderungen speichern', fr: 'Enregistrer' },
  deviceInfoUpdated: { en: 'Device info updated!', et: 'Seadme info uuendatud!' },
  edit: { en: 'Edit', et: 'Muuda', de: 'Bearbeiten', fr: 'Modifier', es: 'Editar', it: 'Modifica', no: 'Rediger', sv: 'Redigera' },
  // ============ AUTO-GENERATED TRANSLATIONS ============
  step1AllowRestrictedSettings: { en: '1. Allow Restricted Settings', et: '1. Luba piiratud seaded' },
  step1OpenAccessibility: { en: '1. Open Accessibility', et: '1. Ava juurdepääs' },
  step1OpenAppInfo: { en: '1. Open App Info', et: '1. Ava rak. info' },
  step1SelectOrCreateClient: { en: '1. Select or Create Client', et: '1. Vali või loo klient' },
  step2LoanDetails: { en: '2. Loan Details', et: '2. Laenu detailid' },
  step2OpenAccessibility: { en: '2. Open Accessibility', et: '2. Ava juurdepääs' },
  step2OpenAppInfo: { en: '2. Open App Info', et: '2. Ava rakenduse info' },
  step2OpenSettings: { en: '2. Open Settings', et: '2. Ava seaded' },
  step3OpenAccessibility: { en: '3. Open Accessibility', et: '3. Ava juurdepääs' },
  step6monthRevenueTrend: { en: '6-Month Revenue Trend', et: '6-kuu tulude trend' },
  accessibility: { en: 'Accessibility', et: 'Juurdepääs' },
  accountRemoved: { en: 'Account Removed', et: 'Konto eemaldatud' },
  actions: { en: 'Actions', et: 'Tegevusi' },
  active: { en: 'active', et: 'aktiivne' },
  active2: { en: 'Active', et: 'Aktiivne' },
  activeLoan: { en: 'Active Loan', et: 'Aktiivne laen' },
  activeLoans: { en: 'Active Loans', et: 'Aktiivsed laenud' },
  add: { en: 'Add', et: 'Lisa' },
  addLoan: { en: 'Add Loan', et: 'Lisa laen' },
  addNewLoan: { en: 'Add New Loan', et: 'Lisa uus laen' },
  addUser: { en: 'Add User', et: 'Lisa kasutaja' },
  address: { en: 'Address', et: 'Aadress' },
  admin: { en: 'admin', et: 'administraator' },
  admin2: { en: 'Admin', et: 'Administraator' },
  adminModeOff: { en: 'Admin mode OFF', et: 'Admin režiim VÄLJAS' },
  adminModeOn: { en: 'Admin mode ON', et: 'Admin režiim SEES' },
  administrator: { en: 'Administrator', et: 'Administraator' },
  admins: { en: 'Admins', et: 'Adminid' },
  advancedMetrics: { en: 'Advanced Metrics', et: 'Täiendavad näitajad' },
  ago: { en: 'ago', et: 'tagasi' },
  aiIsAnalyzingYourBankStatement: { en: 'AI is analyzing your bank statement', et: 'AI analüüsib teie pangaväljavõtet' },
  aipoweredIncomeexpenseAnalysis: { en: 'AI-powered income/expense analysis', et: 'AI-põhine tulu/kulu analüüs' },
  allAdmins: { en: 'All Admins', et: 'Kõik adminid' },
  allClientsAreRegistered: { en: 'All clients are registered', et: 'Kõik kliendid on registreeritud' },
  allDevicesAreConnected: { en: 'All devices are connected', et: 'Kõik seadmed on ühendatud' },
  allMonths: { en: 'All Months', et: 'Kõik kuud' },
  allPaid: { en: 'All Paid', et: 'Kõik makstud' },
  allPermissionsAreGrantedDoYou: { en: 'All permissions are granted. Do you want to activate Device Admin mode? This will protect the device and cannot be disabled without administrator permission.', et: 'Kõik õigused on lubatud. Kas soovite aktiveerida seadme administraatori režiimi? See kaitseb seadet ja seda ei saa keelata ilma administraatori loata.' },
  alreadyDone: { en: 'Already Done', et: 'Juba tehtud' },
  amountDueWithInterest: { en: 'Amount Due (with Interest)', et: 'Tagasimakse intressiga' },
  amountGiven: { en: 'Amount Given', et: 'Laen antud' },
  amountU20ac: { en: 'Amount (\u20AC)', et: 'Summa (\u20AC)' },
  analysisComplete: { en: 'Analysis Complete', et: 'Analüüs valmis' },
  analytics: { en: 'Analytics', et: 'Analüütika' },
  analyzing: { en: 'Analyzing...', et: 'Analüüsin...' },
  apply: { en: 'Apply', et: 'Rakenda' },
  applyTheseSettingsToAllExisting: { en: 'Apply these settings to all existing clients?', et: 'Kas rakendada need seaded kõikidele olemasolevatele klientidele?' },
  applyToAllClients: { en: 'Apply to All Clients', et: 'Rakenda kõikidele klientidele' },
  archived: { en: 'Archived', et: 'Arhiveeritud' },
  areYouSure: { en: 'Are you sure?', et: 'Kas oled kindel?' },
  areYouSureThisWillAlso: { en: 'Are you sure? This will also allow app uninstall on the device.', et: 'Kas olete kindel? See lubab ka rakenduse desinstallimise.' },
  areYouSureYouWantTo: { en: 'Are you sure you want to send reminders to all clients with push tokens?', et: 'Kas olete kindel, et soovite saata meeldetuletused kõigile klientidele?' },
  areYouSureYouWantTo2: { en: 'Are you sure you want to disconnect Google Drive?', et: 'Kas oled kindel, et soovid Google Drive ühenduse katkestada?' },
  assign: { en: 'Assign', et: 'Määra' },
  assignCredits: { en: 'Assign Credits', et: 'Määra krediite' },
  atRisk: { en: 'At Risk', et: 'Ohus' },
  auditLog: { en: 'Audit Log', et: 'Tegevuste logi' },
  autoStart: { en: 'Auto Start', et: 'Autostart' },
  autolockAfterClientautolockgracedays3DaysOverdue: { en: 'Auto-lock after ${client.auto_lock_grace_days || 3} days overdue', et: 'Automaatne lukustus ${client.auto_lock_grace_days || 3} p\u00e4eva p\u00e4rast t\u00e4htaega' },
  autolockEnabled: { en: 'Auto-Lock Enabled', et: 'Automaatne lukustus' },
  automaticSetup: { en: 'Automatic Setup', et: 'Automaatne seadistus' },
  back: { en: 'Back', et: 'Tagasi' },
  backupFailed: { en: 'Backup failed', et: 'Varundamine ebaõnnestus' },
  backupNow: { en: 'Backup Now', et: 'Varunda kohe' },
  backupSuccessfulDemo: { en: 'Backup Successful (Demo)', et: 'Varundamine õnnestus (Demo)' },
  badLoans: { en: 'Bad Loans', et: 'Halvad laenud' },
  balance: { en: 'Balance', et: 'Saldo' },
  bank: { en: 'Bank', et: 'Pank' },
  bankStatementAnalyzer: { en: 'Bank Statement Analyzer', et: 'Pangaväljavõtte analüüs' },
  batteryOptimization: { en: 'Battery Optimization', et: 'Aku optim.' },
  birthNumber: { en: 'Birth Number', et: 'Isikukood' },
  calculateLoanPayments: { en: 'Calculate loan payments', et: 'Arvuta laenumaksed' },
  calculatePreview: { en: 'Calculate Preview', et: 'Arvuta eelvaade' },
  calculatedResults: { en: 'Calculated Results', et: 'Arvutatud tulemused' },
  cannotDeleteYourOwnAccount: { en: 'Cannot delete your own account', et: 'Ei saa kustutada enda kontot' },
  card: { en: 'Card', et: 'Kaart' },
  cash: { en: 'Cash', et: 'Sularaha' },
  change: { en: 'Change', et: 'Muuda' },
  clientCreatedGoToClientDetails: { en: 'Client created! Go to client details to generate registration key.', et: 'Klient lisatud! Minge kliendi detailide juurde, et genereerida registreerimiskood.' },
  clientInfoUpdated: { en: 'Client info updated', et: 'Kliendi andmed uuendatud' },
  clientLocations: { en: 'Client Locations', et: 'Klientide asukohad' },
  clientMap: { en: 'Client Map', et: 'Kliendi kaart' },
  clientName: { en: 'Client name', et: 'Kliendi nimi' },
  clientPortal: { en: 'Client Portal', et: 'Kliendi portaal' },
  clientStatusDistribution: { en: 'Client Status Distribution', et: 'Klientide staatus' },
  clientsDefaulted7Days: { en: 'clients defaulted (>7 days)', et: 'klienti maksejõuetu (>7 päeva)' },
  clientsNeedAttention: { en: 'clients need attention', et: 'klienti vajab tähelepanu' },
  close: { en: 'Close', et: 'Sulge' },
  closing: { en: 'Closing', et: 'Lõppsaldo' },
  collected: { en: 'Collected', et: 'Kogutud' },
  collectionOverview: { en: 'Collection Overview', et: 'Kogumise ülevaade' },
  collectionRate: { en: 'Collection Rate', et: 'Laekumismäär' },
  completed: { en: 'Completed', et: 'Lõpetatud' },
  confirm: { en: 'Confirm', et: 'Kinnita' },
  confirmNewPassword: { en: 'Confirm new password', et: 'Kinnita uus parool' },
  connect: { en: 'Connect', et: 'Ühenda' },
  connectGoogleDrive: { en: 'Connect Google Drive', et: 'Ühenda Google Drive' },
  connected: { en: 'Connected', et: 'Ühendatud' },
  connectedDemo: { en: 'Connected (Demo)', et: 'Ühendatud (Demo)' },
  coordinates: { en: 'Coordinates', et: 'Koordinaadid' },
  count: { en: 'Count', et: 'Arv' },
  createLoan: { en: 'Create Loan', et: 'Loo laen' },
  creditBalance: { en: 'Credit Balance', et: 'Krediidi saldo' },
  creditRecommendation: { en: 'Credit Recommendation', et: 'Krediidisoovitus' },
  creditsCreditsAssignedToSelectedadminusername: { en: '${credits} credits assigned to ${selectedAdmin.username}', et: '${credits} krediiti määratud kasutajale ${selectedAdmin.username}' },
  creditsMustBeAPositiveNumber: { en: 'Credits must be a positive number', et: 'Krediitide arv peab olema positiivne number' },
  critical: { en: 'Critical', et: 'Kriitiline' },
  currentCredits: { en: 'Current credits: ', et: 'Praegused krediidid: ' },
  currentPassword2: { en: 'Current password', et: 'Praegune parool' },
  d: { en: 'd', et: 'p' },
  dark: { en: 'Dark', et: 'Tume' },
  dashboard: { en: 'Dashboard', et: 'Avaleht' },
  date: { en: 'Date:', et: 'Kuupäev:' },
  days: { en: 'Days', et: 'Päevi' },
  days2: { en: 'days', et: 'päeva' },
  daysBeforeAutolock: { en: 'Days before auto-lock', et: 'Päevi enne automaatset lukustust' },
  daysOverdue: { en: 'days overdue', et: 'p\u00e4eva \u00fcle t\u00e4htaja' },
  daysOverdue2: { en: 'Days Overdue', et: 'Hilinenud päevi' },
  daysUntilDue: { en: 'Days Until Due', et: 'Päevi tähtajani' },
  debttoincomeRatio: { en: 'Debt-to-Income Ratio', et: 'Võla/tulu suhe' },
  defaulted: { en: 'Defaulted', et: 'Maksejõuetu' },
  deleteAdmin: { en: 'Delete Admin', et: 'Kustuta administraator' },
  deviceAdminWasDisabledThisIs: { en: 'Device admin was disabled. This is a security violation. Please re-enable immediately.', et: 'Seadme administraator keelati. See on turvarikkumine. Palun lubage uuesti.' },
  deviceHeartbeat: { en: 'Device Heartbeat', et: 'Seadmete olek' },
  deviceIsNowProtectedAndCan: { en: 'Device is now protected and can be locked', et: 'Seade on nüüd kaitstud ja lukustatav' },
  deviceManagement: { en: 'Device Management', et: 'Seadmehaldus' },
  deviceOverview: { en: 'Device Overview', et: 'Seadmete ülevaade' },
  deviceProtection: { en: 'Device Protection', et: 'Seadme kaitse' },
  deviceProtectionActive: { en: 'Device protection active', et: 'Seadme kaitse aktiivne' },
  deviceProtectionRequired: { en: 'Device Protection Required', et: 'Seadme kaitse vajalik' },
  deviceSetup: { en: 'Device Setup', et: 'Seadme seadistus' },
  deviceWillSetUpAutomatically: { en: 'Device will set up automatically', et: 'Seade seadistatakse automaatselt' },
  devicesUnresponsive2h: { en: 'device(s) unresponsive >2h', et: 'seadet pole vastanud >2h' },
  diagnosticReport: { en: 'Diagnostic Report', et: 'Diagnostika aruanne' },
  diffdaysDaysAgo: { en: '${diffDays} days ago', et: '${diffDays} päeva tagasi' },
  diffhoursHoursAgo: { en: '${diffHours} hours ago', et: '${diffHours} tundi tagasi' },
  diffminsMinutesAgo: { en: '${diffMins} minutes ago', et: '${diffMins} minutit tagasi' },
  disbursed: { en: 'Disbursed', et: 'Väljastus' },
  disbursements: { en: 'Disbursements', et: 'Väljastused' },
  disconnect: { en: 'Disconnect', et: 'Katkesta' },
  disposableIncome: { en: 'Disposable Income', et: 'Vaba sissetulek' },
  doYouWantToConnectGoogle: { en: 'Do you want to connect Google Drive for backup?\n\n⚠️ This is currently a demo version', et: 'Kas soovid ühendada Google Drive varundamiseks?\n\n⚠️ See on praegu demo versioon' },
  download: { en: 'Download', et: 'Laadi alla' },
  due: { en: 'Due', et: 'Võlg' },
  dueDateMustBeAtLeast: { en: 'Due date must be at least tomorrow', et: 'Tähtaeg peab olema vähemalt homme' },
  dueThisMonth: { en: 'Due This Month', et: 'Selle kuu maksed tasuda' },
  editClientInfo: { en: 'Edit Client Info', et: 'Muuda kliendi andmeid' },
  editLoanTerms: { en: 'Edit Loan Terms', et: 'Muuda laenu tingimusi' },
  editProfile: { en: 'Edit Profile', et: 'Muuda profiili' },
  emailAddress2: { en: 'Email address', et: 'E-posti aadress' },
  enableDeviceAdmin: { en: 'Enable Device Admin', et: 'Luba seadme administraator' },
  enableNow: { en: 'Enable Now', et: 'Luba kohe' },
  engb: { en: 'en-GB', et: 'et-EE' },
  enterAddress: { en: 'Enter address', et: 'Sisesta aadress' },
  enterBirthNumber: { en: 'Enter birth number', et: 'Sisesta isikukood' },
  enterMonthlyInterestRate: { en: 'Enter monthly interest rate', et: 'Sisesta intressimäär' },
  enterprise: { en: 'Enterprise', et: 'Ettevõte' },
  enus: { en: 'en-US', et: 'et-EE' },
  existing: { en: 'Existing', et: 'Olemasolev' },
  expenseCategories: { en: 'Expense Categories', et: 'Kulu kategooriad' },
  expenses: { en: 'Expenses', et: 'Kulud' },
  exportDiagnostics: { en: 'Export Diagnostics', et: 'Ekspordi diagnostika' },
  exportPdf: { en: 'Export PDF', et: 'Ekspordi PDF' },
  exportReport: { en: 'Export Report', et: 'Ekspordi aruanne' },
  factoryResetThePhone: { en: 'Factory reset the phone', et: 'Tehke telefonil tehaseseaded' },
  failedToApplySettings: { en: 'Failed to apply settings', et: 'Seadete rakendamine ebaõnnestus' },
  failedToCalculateLateFees: { en: 'Failed to calculate late fees', et: 'Viiviste arvutamine ebaõnnestus' },
  failedToGenerateReport: { en: 'Failed to generate report', et: 'Aruande koostamine ebaõnnestus' },
  failedToLoadStatus: { en: 'Failed to load status', et: 'Staatuse laadimine ebaõnnestus' },
  failedToSaveSettings: { en: 'Failed to save settings', et: 'Seadete salvestamine ebaõnnestus' },
  features: { en: 'Features', et: 'Funktsioonid' },
  file: { en: 'File', et: 'Fail' },
  filterByAdmin: { en: 'Filter by Admin:', et: 'Filtreeri admini järgi:' },
  filterClients: { en: 'Filter Clients', et: 'Filtreeri kliendid' },
  filterOverdue: { en: 'Filter: Overdue', et: 'Filtreeritud: võlglased' },
  filterPaid: { en: 'Filter: Paid', et: 'Filtreeritud: tasutud' },
  financialAnalyticsReports: { en: 'Financial analytics & reports', et: 'Finantsanalüütika ja aruanded' },
  financialBreakdown: { en: 'Financial Breakdown', et: 'Finantside jaotus' },
  financialOverview: { en: 'Financial Overview', et: 'Finantsülevaade' },
  firstName: { en: 'First name', et: 'Eesnimi' },
  gamblingTransactionsDetected: { en: 'Gambling transactions detected', et: 'Hasartmängu tehingud tuvastatud' },
  generate: { en: 'Generate', et: 'Genereeri' },
  generateAPdfReportWithDevice: { en: 'Generate a PDF report with device info, permission status, logs, and API errors.', et: 'Koosta PDF raport seadme info, õiguste, logide ja API vigadega.' },
  generateKey: { en: 'Generate key', et: 'Genereeri võti' },
  generateNewKey: { en: 'Generate New Key', et: 'Genereeri uus v\u00f5ti' },
  generatedBy: { en: 'Generated by:', et: 'Koostaja:' },
  given: { en: 'Given', et: 'Antud' },
  googleDriveBackup: { en: 'Google Drive Backup', et: 'Google Drive varundus' },
  googleDriveConnectedSuccessfullySimulation: { en: 'Google Drive connected successfully (simulation)', et: 'Google Drive on edukalt ühendatud (simulatsioon)' },
  gracePeriodDays: { en: 'Grace Period (days)', et: 'Ooteaeg (päevad)' },
  gracePeriodMustBe1365Days: { en: 'Grace period must be 1-365 days', et: 'Ooteaeg peab olema 1-365 päeva' },
  grantAdminPermissionsInTheNext: { en: 'Grant admin permissions in the next dialog', et: 'Lubage administraatori õigused järgmises dialoogis' },
  high: { en: 'High', et: 'Kõrge' },
  holder: { en: 'Holder', et: 'Omanik' },
  income: { en: 'Income', et: 'Tulud' },
  incomeCategories: { en: 'Income Categories', et: 'Tulu kategooriad' },
  incomeStability: { en: 'Income stability', et: 'Sissetuleku stabiilsus' },
  incorrectCode: { en: 'Incorrect code', et: 'Vale kood' },
  installLoanClientAppOnThe: { en: 'Install Loan Client app on the phone', et: 'Installige Loan Client rakendus telefonile' },
  instructions: { en: 'Instructions', et: 'Juhised' },
  interest: { en: 'Interest', et: 'Intress' },
  interestEarned: { en: 'Interest Earned', et: 'Intressitulu' },
  interestMonthly: { en: 'Interest (Monthly)', et: 'Intress (kuus)' },
  interestRate: { en: 'Interest Rate', et: 'Intressimäär' },
  interestRateMonthly: { en: 'Interest Rate Monthly (%)', et: 'Igakuine intressimäär (%)' },
  interestRatePerMonth: { en: 'Interest Rate (% per month)', et: 'Intressimäär (% kuus)' },
  invalidPhoneOrRegistrationCode: { en: 'Invalid phone or registration code', et: 'Vale telefon või registreerimiskood' },
  itemtamperattemptsTamperAttempts: { en: '${item.tamper_attempts} tamper attempts', et: '${item.tamper_attempts} rikkumiskatset' },
  justNow: { en: 'just now', et: 'just nüüd' },
  justNow2: { en: 'Just now', et: 'Just nüüd' },
  keyNotGenerated: { en: 'Key: not generated', et: 'Võti: pole genereeritud' },
  keyNotGeneratedYet: { en: 'Key not generated yet', et: 'Võtit pole veel genereeritud' },
  last7Days: { en: 'Last 7 Days', et: 'Viimased 7 päeva' },
  lastBackup: { en: 'Last backup: ', et: 'Viimane varundus: ' },
  lastName: { en: 'Last name', et: 'Perekonnanimi' },
  lastSeen: { en: 'Last seen: ', et: 'Viimati nähtud: ' },
  lastSeen2: { en: 'Last seen', et: 'Viimane ühendus' },
  lateFee: { en: 'Late Fee', et: 'Viivis' },
  lateFeeAmount: { en: 'Late Fee Amount', et: 'Viivise summa' },
  lateFeeAutolock: { en: 'Late Fee & Auto-Lock', et: 'Viivis ja automaatne lukustus' },
  lateFeePercent: { en: 'Late Fee Percent', et: 'Viivise protsent' },
  lateFeePercentMustBe0100: { en: 'Late fee percent must be 0-100', et: 'Viivise protsent peab olema 0-100' },
  lateFees: { en: 'Late Fees', et: 'Viivised' },
  lateFeesCalculatedDataupdatedcount0Clients: { en: 'Late fees calculated! ${data.updated_count || 0} clients updated.', et: 'Viivised arvutatud! ${data.updated_count || 0} klienti uuendatud.' },
  later: { en: 'Later', et: 'Hiljem' },
  light: { en: 'Light', et: 'Hele' },
  listings: { en: 'listings', et: 'kuulutust' },
  loading: { en: 'Loading...', et: 'Laadimine...' },
  loadingData: { en: 'Loading data...', et: 'Laen andmeid...' },
  loadingSilentClients: { en: 'Loading silent clients...', et: 'Laadin kadunud kliente...' },
  loanAmountCurrencysymbol: { en: 'Loan Amount (${currencySymbol})', et: 'Laenusumma (${currencySymbol})' },
  loanAmountU20ac: { en: 'Loan Amount (\u20AC)', et: 'Laenusumma (\u20AC)' },
  loanCalculator: { en: 'Loan Calculator', et: 'Laenukalkulaator' },
  loanDisbursement: { en: 'Loan disbursement', et: 'Laenu väljastamine' },
  loanGivenDate: { en: 'Loan Given Date', et: 'Laenu antud kuupäev' },
  loanHistory: { en: 'Loan History', et: 'Laenu ajalugu' },
  loanManagement: { en: 'Loan Management', et: 'Laenuhaldus' },
  loanManagementSystem: { en: 'Loan Management System', et: 'Laenuhaldussüsteem' },
  loanOverview: { en: 'Loan Overview', et: 'Laenu \u00fclevaade' },
  loanPaymentsDetected: { en: 'Loan payments detected', et: 'Laenumaksed tuvastatud' },
  loanPlanOptional: { en: 'Loan Plan (Optional)', et: 'Laenuplaan (valikuline)' },
  loanPlans: { en: 'Loan Plans', et: 'Laenuplaanid' },
  loanProgress: { en: 'Loan Progress', et: 'Laenu progress' },
  loanStartDate: { en: 'Loan Start Date', et: 'Laenu alguskuup\u00e4ev' },
  loanUpdatednnmonthlyEmiFormatamountdataloandetailsmonthlyemintotalFormatamountdataloandetailstotalamountdue: { en: 'Loan updated!\n\nMonthly EMI: ${formatAmount(data.loan_details.monthly_emi)}\nTotal: ${formatAmount(data.loan_details.total_amount_due)}', et: 'Laen uuendatud!\n\nKuumakse: ${formatAmount(data.loan_details.monthly_emi)}\nKokku: ${formatAmount(data.loan_details.total_amount_due)}' },
  loans: { en: 'Loans', et: 'Laenud' },
  loansArchived: { en: 'Loans Archived', et: 'Arhiveeritud laene' },
  loansAreAutomaticallyArchivedWhenFully: { en: 'Loans are automatically archived when fully paid', et: 'Laenud arhiveeritakse automaatselt, kui need on täielikult tasutud' },
  location: { en: 'Location', et: 'Asukoht' },
  lockDeviceAutomatically: { en: 'Lock device automatically', et: 'Lukusta seade automaatselt' },
  locked2: { en: 'locked', et: 'lukustatud' },
  lockunlockDevices: { en: 'Lock/unlock devices', et: 'Lukusta/vabasta seadmeid' },
  loginFailed: { en: 'Login Failed', et: 'Sisselogimine ebaõnnestus' },
  low: { en: 'Low', et: 'Madal' },
  lowCreditsContactSuperadminForMore: { en: 'Low credits. Contact superadmin for more.', et: 'Krediit hakkab lõppema. Pöördu peaadmini poole.' },
  manageAllClientsAndDevices: { en: 'Manage all clients and devices', et: 'Halda kõiki kliente ja seadmeid' },
  manageLoanPlans: { en: 'Manage loan plans', et: 'Halda laenuplaane' },
  markAllRead: { en: 'Mark all read', et: 'Märgi loetuks' },
  marketPriceMedian: { en: 'Market Price (median)', et: 'Turuhind (mediaan)' },
  mathmax1DiffmonthsMonths: { en: '~${Math.max(1, diffMonths)} months', et: '~${Math.max(1, diffMonths)} kuud' },
  medium: { en: 'Medium', et: 'Keskmine' },
  modelAndroidVernnaSystemDialogWill: { en: '${model} (Android ${ver})\n\nA system dialog will appear.\nAllow the app to run unrestricted in the background.', et: '${model} (Android ${ver})\n\nSüsteemi dialoog avaneb.\nLubage rakendusel töötada piiranguteta taustal.' },
  month: { en: 'Month', et: 'Kuu' },
  monthly: { en: 'Monthly', et: 'Kuus' },
  monthlyBreakdown: { en: 'Monthly Breakdown', et: 'Igakuine jaotus' },
  monthlyInterestEarnedLast6Months: { en: 'Monthly Interest Earned (Last 6 Months)', et: 'Igakuine intressitulu (viimased 6 kuud)' },
  monthlyInterestIncome: { en: 'Monthly Interest Income', et: 'Igakuine intressitulu' },
  monthlyInterestRate: { en: 'Monthly Interest Rate (%)', et: 'Intressim\u00e4\u00e4r kuus (%)' },
  monthlyRevenue: { en: 'Monthly Revenue', et: 'Igakuine tulu' },
  months: { en: 'months', et: 'kuud' },
  myData: { en: 'My Data', et: 'Minu andmed' },
  name: { en: 'Name', et: 'Nimi' },
  nameIsRequired: { en: 'Name is required', et: 'Nimi on kohustuslik' },
  netChange: { en: 'Net Change', et: 'Netomuutus' },
  networkConnectionError: { en: 'Network connection error', et: 'Võrguühenduse viga' },
  never: { en: 'Never', et: 'Pole varundatud' },
  neverConnected: { en: 'Never connected', et: 'Kunagi pole ühendunud' },
  new: { en: 'New', et: 'Uus' },
  newCredits: { en: 'New credits', et: 'Uued krediidid' },
  newCustomers: { en: 'New Customers', et: 'Uued kliendid' },
  newLoans: { en: 'New Loans', et: 'Uued laenud' },
  newPassword2: { en: 'New password', et: 'Uus parool' },
  newPasswordMustBeAtLeast: { en: 'New password must be at least 6 characters', et: 'Uus parool peab olema vähemalt 6 tähemärki' },
  newRegistrationCodeDataregistrationcode: { en: 'New registration code: ${data.registration_code}', et: 'Uus registreerimiskood: ${data.registration_code}' },
  newRoletextCreatedSuccessfully: { en: 'New ${roleText} created successfully', et: 'Uus ${roleText} loodud' },
  next3Days: { en: 'Next 3 days', et: '3 päeva' },
  nextPayment: { en: 'Next Payment', et: 'Järgmine makse' },
  nextPayment2: { en: 'Next payment', et: 'Järgmine makse' },
  noAddress: { en: 'No address', et: 'Aadress puudub' },
  noArchivedLoans: { en: 'No archived loans', et: 'Arhiveeritud laene pole' },
  noArchivedLoansFound: { en: 'No archived loans found', et: 'Arhiveeritud laene ei leitud' },
  noCredits: { en: 'No Credits', et: 'Krediidid puuduvad' },
  noDataAvailableYet: { en: 'No data available yet', et: 'Andmeid pole veel' },
  noLocationsFound: { en: 'No locations found', et: 'Asukohti pole' },
  noLogsFound: { en: 'No logs found', et: 'Tegevusi ei leitud' },
  noMessagesYet: { en: 'No messages yet', et: 'Vestlus on tühi' },
  noNotifications: { en: 'No notifications', et: 'Teavitusi pole' },
  noPaymentsYet: { en: 'No payments yet', et: 'Makseid pole' },
  noPendingReminders: { en: 'No pending reminders', et: 'Ootavaid meeldetuletusi pole' },
  noPushToken: { en: 'No Push Token', et: 'Pole push tokenit' },
  noResultsFound: { en: 'No results found', et: 'Tulemusi ei leitud' },
  noSilentClients: { en: 'No silent clients!', et: 'Kadunud kliente pole!' },
  noTransactionsFound: { en: 'No transactions found', et: 'Tehinguid ei leitud' },
  noTrendDataAvailableYet: { en: 'No trend data available yet', et: 'Trendiandmeid pole veel' },
  notConnected: { en: 'Not Connected', et: 'Ühendamata' },
  notLoggedIn: { en: 'Not logged in', et: 'Pole sisse logitud' },
  notesOptional: { en: 'Notes (Optional)', et: 'M\u00e4rkmed (valikuline)' },
  notifListener: { en: 'Notif. Listener', et: 'Teavit. kuulaja' },
  notificationListener: { en: 'Notification Listener', et: 'Teavituste kuulaja' },
  notifications: { en: 'Notifications', et: 'Teavitused' },
  numberOfPayments: { en: 'Number of Payments', et: 'Maksete arv' },
  ocrMayTakeUpTo30s: { en: 'OCR may take up to ~30s', et: 'OCR võib võtta ~30s' },
  onTime: { en: 'On Time', et: 'Õigel ajal' },
  onWelcomeScreenTap6Times: { en: 'On welcome screen, tap 6 times', et: 'Tervitusekraanil puudutage 6 korda' },
  online: { en: 'Online', et: 'Aktiivne' },
  onlyPdfAndAsiceFilesSupported: { en: 'Only .pdf and .asice files supported', et: 'Ainult .pdf ja .asice failid' },
  openInMaps: { en: 'Open in Maps', et: 'Ava kaardil' },
  openSettings: { en: 'Open Settings', et: 'Ava seaded' },
  openTheAppAndEnterThe: { en: 'Open the app and enter the registration code', et: 'Avage rakendus ja sisestage registreerimiskood' },
  opening: { en: 'Opening', et: 'Algsaldo' },
  outstanding: { en: 'Outstanding', et: 'Jääk' },
  overdue: { en: 'Overdue', et: 'Võlglased' },
  overdue2: { en: 'overdue', et: 'päeva üle' },
  overlay: { en: 'Overlay', et: 'Ülekate' },
  paid: { en: 'Paid', et: 'Makstud' },
  paid2: { en: 'paid', et: 'makstud' },
  passwordChangedSuccessfully: { en: 'Password changed successfully', et: 'Parool muudetud' },
  passwordsDoNotMatch: { en: 'Passwords do not match', et: 'Paroolid ei kattu' },
  payment: { en: 'Payment', et: 'Makse' },
  paymentHistory: { en: 'Payment History', et: 'Makseajalugu' },
  paymentMethod: { en: 'Payment Method', et: 'Makseviis' },
  paymentNotes: { en: 'Payment notes...', et: 'Makse m\u00e4rkmed...' },
  paymentOverdue: { en: 'Payment Overdue!', et: 'Makse on hilinenud!' },
  paymentRecordednnpaidFormatamountpaidamountnoutstandingFormatamountoutstandingbalance: { en: 'Payment recorded!\n\nPaid: ${formatAmount(paidAmount)}\nOutstanding: ${formatAmount(outstandingBalance)}', et: 'Makse salvestatud!\n\nMakstud: ${formatAmount(paidAmount)}\nJ\u00e4\u00e4k: ${formatAmount(outstandingBalance)}' },
  paymentReminders: { en: 'Payment Reminders', et: 'Maksemuljatused' },
  paymentTimeline: { en: 'Payment Timeline', et: 'Maksete ajatelg' },
  payments: { en: 'Payments', et: 'Makseid' },
  payments2: { en: 'payments', et: 'makset' },
  pdfOrAsiceFiles: { en: '.pdf or .asice files', et: '.pdf või .asice failid' },
  pdfSavedUri: { en: 'PDF saved: ${uri}', et: 'PDF salvestatud: ${uri}' },
  percentOfMonthlyPayment: { en: 'Percent of monthly payment', et: 'Protsent igakuisest maksest' },
  period: { en: 'Period', et: 'Periood' },
  phone: { en: 'Phone', et: 'Telefon' },
  phoneNumber2: { en: 'Phone number', et: 'Telefoninumber' },
  pleaseConnectGoogleDriveFirst: { en: 'Please connect Google Drive first', et: 'Palun ühenda esmalt Google Drive' },
  pleaseEnterAValidInterestRate: { en: 'Please enter a valid interest rate', et: 'Palun sisesta kehtiv intressimäär' },
  pleaseEnterAValidLoanAmount: { en: 'Please enter a valid loan amount', et: 'Palun sisesta kehtiv laenusumma' },
  pleaseEnterCreditsAmount: { en: 'Please enter credits amount', et: 'Palun sisesta krediitide arv' },
  pleaseEnterPaymentAmount: { en: 'Please enter payment amount', et: 'Palun sisesta summa' },
  pleaseEnterPhoneAndRegistrationCode: { en: 'Please enter phone and registration code', et: 'Palun sisestage telefon ja registreerimiskood' },
  pleaseEnterYourName: { en: 'Please enter your name', et: 'Palun sisesta nimi' },
  pleaseFillAllClientFields: { en: 'Please fill all client fields', et: 'Palun täida kõik kliendi väljad' },
  pleaseFillAllFields: { en: 'Please fill all fields', et: 'Palun täida kõik väljad' },
  pleaseFillAllRequiredFields: { en: 'Please fill all required fields', et: 'Palun t\u00e4ida k\u00f5ik v\u00e4ljad' },
  pleaseLogInAgain: { en: 'Please log in again', et: 'Palun logige uuesti sisse' },
  pleaseSelectAClient: { en: 'Please select a client', et: 'Palun vali klient' },
  pleaseSelectADueDate: { en: 'Please select a due date', et: 'Palun vali tähtaeg' },
  prefilledFromPreviousLoanAdjustAs: { en: 'Pre-filled from previous loan. Adjust as needed.', et: 'Eelmise laenu andmed on eeltäidetud. Muutke vajadusel.' },
  principal: { en: 'Principal', et: 'Põhiosa' },
  principalDisbursed: { en: 'Principal Disbursed', et: 'Väljastatud põhiosa' },
  processingFees: { en: 'Processing Fees', et: 'Töötlustasud' },
  processingSebOcr: { en: 'Processing SEB OCR...', et: 'SEB OCR töötleb faili...' },
  profileUpdatedSuccessfully: { en: 'Profile updated successfully', et: 'Profiil uuendatud' },
  profitInterest: { en: 'Profit (Interest)', et: 'Kasum (intress)' },
  profitReport: { en: 'Profit Report', et: 'Kasumiaruanne' },
  profitReport2: { en: 'PROFIT REPORT', et: 'KASUMIARUANNE' },
  profitSummary: { en: 'Profit Summary', et: 'Kasumi kokkuvõte' },
  profitThisMonth: { en: 'Profit (This Month)', et: 'Käesoleva kuu kasum' },
  protectionActive: { en: 'Protection Active', et: 'Kaitse aktiivne' },
  protectionIncomplete: { en: 'Protection Incomplete', et: 'Kaitse mittetäielik' },
  protectionNotActive: { en: 'Protection not active', et: 'Kaitse pole aktiivne' },
  qrCodeType: { en: 'QR Code Type', et: 'QR-koodi tüüp' },
  range: { en: 'Range', et: 'Vahemik' },
  ready: { en: 'Ready', et: 'Valmis' },
  record: { en: 'Record', et: 'Salvesta' },
  recordPayment: { en: 'Record Payment', et: 'Lisa makse' },
  regenerateKey: { en: 'Regenerate key', et: 'Regenereeri võti' },
  registerANewDevice: { en: 'Register a new device', et: 'Registreeri uus seade' },
  registered2: { en: 'registered', et: 'registreeritud' },
  registeredDevicesWillAppearHere: { en: 'Registered devices will appear here', et: 'Registreeritud seadmed ilmuvad siia' },
  regularIncome: { en: 'Regular income', et: 'Regulaarne sissetulek' },
  remaining: { en: 'Remaining', et: 'Jääk' },
  reminderSentToClientname: { en: 'Reminder sent to: ${clientName}', et: 'Meeldetuletus saadetud: ${clientName}' },
  renewLoan: { en: 'Renew Loan', et: 'Uuenda laenu' },
  repeatCustomers: { en: 'Repeat Customers', et: 'Korduvkliendid' },
  reports: { en: 'Reports', et: 'Aruanded' },
  reportsAnalytics: { en: 'Reports & Analytics', et: 'Aruanded ja analüütika' },
  revenue: { en: 'Revenue', et: 'Tulu' },
  revenueThisMonth: { en: 'Revenue (This Month)', et: 'Käesoleva kuu tulu' },
  riskAnalysis: { en: 'Risk Analysis', et: 'Riskianalüüs' },
  riskLevel: { en: 'Risk Level', et: 'Riskitase' },
  roi: { en: 'ROI', et: 'ROI' },
  role: { en: 'Role', et: 'Roll' },
  save: { en: 'Save', et: 'Salvesta' },
  saveSettings: { en: 'Save Settings', et: 'Salvesta seaded' },
  scanTheQrCodeOnA: { en: 'Scan the QR code on a new or factory-reset phone to automatically set up loan protection.', et: 'Skannige QR-kood uuel või tehaseseadetega telefonil, et seadistada laenu kaitse automaatselt.' },
  scanThisQrCode: { en: 'Scan this QR code', et: 'Skannige see QR-kood' },
  score: { en: 'Score', et: 'Krediidiskoor' },
  search: { en: 'Search...', et: 'Otsi...' },
  searchArchivedLoans: { en: 'Search archived loans...', et: 'Otsi arhiveeritud laene...' },
  searchByAmountDateInterest: { en: 'Search by amount, date, interest...', et: 'Otsi summa, kuup\u00e4eva, intressi j\u00e4rgi...' },
  searchClients: { en: 'Search clients...', et: 'Otsi kliente...' },
  searchUsers: { en: 'Search users...', et: 'Otsi kasutajaid...' },
  securityAlert: { en: 'Security Alert', et: 'Turvahoiatus' },
  selectAdmin: { en: 'Select Admin', et: 'Vali admin' },
  selectClient: { en: 'Select Client', et: 'Vali klient' },
  selectDate: { en: 'Select date', et: 'Vali kuup\u00e4ev' },
  selectLoanPlan: { en: 'Select Loan Plan', et: 'Vali laenuplaan' },
  selectMonth: { en: 'Select Month', et: 'Vali kuu' },
  selectPlan: { en: 'Select Plan', et: 'Vali plaan' },
  selectYear: { en: 'Select Year', et: 'Vali aasta' },
  sendAll: { en: 'Send All', et: 'Saada kõik' },
  sendPaymentReminders: { en: 'Send payment reminders', et: 'Saada maksemuljatusi' },
  sendReminder: { en: 'Send Reminder', et: 'Saada meeldetuletus' },
  sendReminders: { en: 'Send Reminders', et: 'Saada meeldetuletused' },
  sendUsAMessageWithYour: { en: 'Send us a message with your question', et: 'Kirjutage meile oma küsimuse' },
  sentDatanotificationssentFailedDatanotificationsfailed: { en: 'Sent: ${data.notifications_sent}, Failed: ${data.notifications_failed}', et: 'Saadetud: ${data.notifications_sent}, Ebaõnnestunud: ${data.notifications_failed}' },
  sessionExpired: { en: 'Session Expired', et: 'Seanss aegunud' },
  settingsAppliedToDataclientsupdatedClients: { en: 'Settings applied to ${data.clients_updated} clients', et: 'Seaded rakendatud ${data.clients_updated} kliendile' },
  settingsSavedSuccessfully: { en: 'Settings saved successfully', et: 'Seaded salvestatud' },
  setupLoan: { en: 'Setup Loan', et: 'Seadista laen' },
  share: { en: 'Share', et: 'Jaga' },
  shareInstructions: { en: 'Share Instructions', et: 'Jaga juhiseid' },
  shareLoanContract: { en: 'Share Loan Contract', et: 'Jaga laenulepingut' },
  sharingNotAvailable: { en: 'Sharing not available', et: 'Jagamine pole saadaval' },
  sharingNotAvailableOnThisDevice: { en: 'Sharing not available on this device', et: 'Jagamine pole saadaval' },
  showingPage1Pagesize1mathminpagePagesize: { en: 'Showing ${(page - 1) * pageSize + 1}-${Math.min(page * pageSize, filteredTransactions.length)} of ${filteredTransactions.length}', et: 'Näitan ${(page - 1) * pageSize + 1}-${Math.min(page * pageSize, filteredTransactions.length)} / ${filteredTransactions.length}' },
  silent: { en: 'Silent', et: 'Kadunud' },
  simple: { en: 'Simple', et: 'Lihtne' },
  soon: { en: 'Soon', et: 'Peagi' },
  startDate: { en: 'Start Date', et: 'Alguskuupäev' },
  status: { en: 'Status', et: 'Olek' },
  strikeRate: { en: 'Strike Rate', et: 'Edukusmäär' },
  superadmin: { en: 'Superadmin', et: 'Peaadmin' },
  support: { en: 'Support', et: 'Tugi' },
  tamperingDetectedDeviceHasBeenLocked: { en: 'Tampering detected. Device has been locked.', et: 'Tuvastati manipulatsioon. Seade on lukustatud.' },
  tenure: { en: 'Tenure', et: 'Periood' },
  theme: { en: 'Theme', et: 'Teema' },
  thisDeviceDoesNotSupportSharing: { en: 'This device does not support sharing.', et: 'Seade ei toeta jagamist.' },
  thisMonth: { en: '(this month)', et: '(sel kuul)' },
  thisMonth2: { en: 'This Month', et: 'Sel kuul' },
  toFullyProtectYourDevicePlease: { en: 'To fully protect your device, please enable the accessibility service. This prevents unauthorized app removal.', et: 'Seadme turvalisuse tagamiseks lubage juurdepääsetavuse teenus. See kaitseb rakendust eemaldamise eest.' },
  toSecureYourDevicePleaseEnable: { en: 'To secure your device, please enable Device Admin permissions.', et: 'Seadme turvaliseks kasutamiseks luba administraatori õigused.' },
  today: { en: 'Today', et: 'Täna' },
  tomorrow: { en: 'Tomorrow', et: 'Homme' },
  totalAmount: { en: 'Total Amount', et: 'Kokku tagasimakse' },
  totalDevices: { en: 'Total Devices', et: 'Seadmeid kokku' },
  totalDisbursed: { en: 'Total Disbursed', et: 'Laenatud kokku' },
  totalDue: { en: 'Total Due', et: 'Kokku maksta' },
  totalInterest: { en: 'Total Interest', et: 'Intress kokku' },
  totalInterestEarned: { en: 'Total Interest Earned', et: 'Kokku intressitulu' },
  totalPaid: { en: 'Total Paid', et: 'Makstud kokku' },
  totalPayable: { en: 'Total Payable', et: 'Kokku tagasi' },
  totalRevenue: { en: 'Total Revenue', et: 'Kogutulu' },
  transactions: { en: 'Transactions', et: 'Tehingud' },
  transfer: { en: 'Transfer', et: '\u00dclekanne' },
  tryAgain: { en: 'Try Again', et: 'Proovi uuesti' },
  typeAMessage: { en: 'Type a message...', et: 'Kirjuta sõnum...' },
  types: { en: 'Types', et: 'Tüüpe' },
  unknown: { en: 'Unknown', et: 'Pole teada' },
  unread: { en: 'unread', et: 'lugemata' },
  upcoming: { en: 'Upcoming', et: 'Tulemas' },
  updated: { en: 'Updated', et: 'Uuendatud' },
  uploadBankStatement: { en: 'Upload Bank Statement', et: 'Lae üles pangaväljavõte' },
  usageStats: { en: 'Usage Stats', et: 'Kasutuse stat.' },
  usageStatsAccess: { en: 'Usage Stats Access', et: 'Kasutuse statistika' },
  useThePhoneNumberAndCode: { en: 'Use the phone number and code you received during registration', et: 'Kasutage registreerimisel saadud telefoni ja koodi' },
  user: { en: 'user', et: 'kasutaja' },
  user2: { en: 'User', et: 'Kasutaja' },
  userManagement: { en: 'User Management', et: 'Kasutajahaldus' },
  userManagementSettings: { en: 'User management & settings', et: 'Kasutajahaldus ja seaded' },
  viewAndManageClients: { en: 'View and manage clients', et: 'Vaata ja halda kliente' },
  viewClientLocations: { en: 'View client locations', et: 'Vaata klientide asukohti' },
  viewDevices: { en: 'View Devices', et: 'Vaata seadmeid' },
  viewNotifications: { en: 'View notifications', et: 'Vaata teavitusi' },
  viewYourLoanStatus: { en: 'View your loan status', et: 'Vaadake oma laenu staatust' },
  warningFromAdministrator: { en: 'Warning from Administrator', et: 'Hoiatus administraatorilt' },
  weReplyWithin24h: { en: 'We reply within 24h', et: 'Vastame 24h jooksul' },
  welcome2: { en: 'Welcome', et: 'Tere tulemast' },
  withPush: { en: 'with push', et: 'teavitustega' },
  yearly: { en: 'Yearly', et: 'Aastas' },
  yesDelete: { en: 'Yes, Delete', et: 'Jah, kustuta' },
  yesEnable: { en: 'Yes, Enable', et: 'Jah, luba' },
  yesterday: { en: 'Yesterday', et: 'Eile' },
  you: { en: '(you)', et: '(sina)' },
  youHaveNoActiveLoans: { en: 'You have no active loans', et: 'Teil pole aktiivseid laene' },
  youHaveNoCreditsToGenerate: { en: 'You have no credits to generate a key. Please contact the superadmin.', et: 'Teil pole krediite v\u00f5tme genereerimiseks. Palun p\u00f6\u00f6rduge peaadmini poole.' },
  yourAccount: { en: 'Your Account', et: 'Sinu konto' },
  yourAccountHasBeenRemovedBy: { en: 'Your account has been removed by the administrator. You can now uninstall this app.', et: 'Teie konto on administraatori poolt eemaldatud. Saate nüüd rakenduse desinstallida.' },


};

// German-based fallback languages
const germanFallbacks: Language[] = ['de_at', 'de_ch'];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const saved = await AsyncStorage.getItem('app_language');
      if (saved && LANGUAGES.some(l => l.code === saved)) {
        setLanguageState(saved as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('app_language', lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    const entry = translations[key];
    if (!entry) return key;

    // Try exact language match
    if (entry[language]) return entry[language]!;

    // Fallback for German variants -> German
    if (germanFallbacks.includes(language) && entry['de']) return entry['de']!;

    // Final fallback: English
    return entry['en'] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );


export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
